export default [
  {
    id: '5',
    manager: '김용국',
    staff: ['김태양','김용국'],
    product: '30박스올냉장 WSM-830R-3D',
    location: '전라남도 목포시 호남동 10-44 한일약국',
    price: '840,000',
    payment: '미결제',
    status: '대기',
  },
  {
    id: '4',
    manager: '김용국',
    staff: 'kimyongkuk',
    product: '30박스올냉장 WSM-830R-3D',
    location: '전라남도 목포시 석현동 351 목포미래병원',
    price: '840,000',
    payment: '미결제',
    status: '배송중',
  },
  {
    id: '3',
    manager: '김용국',
    staff: '김용국',
    product: '30박스올냉장 WSM-830R-3D',
    location: '전라남도 목포시 산정동 1731-6 예향정',
    price: '840,000',
    payment: '미결제',
    status: '배송완료',
  },
  {
    id: '2',
    manager: '김용국',
    staff: '김용국',
    product: '6자 냉장테이블 (LT-1834R)',
    location: '전라남도 목포시 산정동 1791-5 김가네손짜장',
    price: '840,000',
    payment: '결제완료',
    status: '배송완료',
  },
  {
    id: '1',
    manager: '김용국',
    staff: '김용국',
    product: '30박스올냉장 WSM-830R-3D',
    location: '전라남도 목포시 산정동 1772-4 목향식육식당',
    price: '840,000',
    payment: '결제완료',
    status: '배송완료',
  },


];
